### ISSUE TITLE
Can not receive serial from Nextion Buttons

### ISSUE THREAD

**Issue by talkyoo** [programmer372/micropython-nextion#8]
Hello,

I got buttons defined, but do not receive anything back.
but sending to the nextion works great and data is shown.

![image](https://user-images.githubusercontent.com/43812375/147921166-a74a5238-e7c7-4af3-ad92-cca6b20f45cc.png)

here is my simple code.

what do I miss about display.read()?

`from machine import Pin, I2C
from time import sleep
from nextion import nextion
import BME280

i2c = I2C(scl=Pin(26), sda=Pin(27), freq=10000)

display = nextion(17, 16, 9600) #TX=17 RX=16

while True:
  bme = BME280.BME280(i2c=i2c)
  temp = bme.temperature
  hum = bme.humidity
  pres = bme.pressure
  
 
  show_temp = 't1.txt='+'"'+temp+'"'
  show_humi = 't2.txt='+'"'+hum+'"'
  display.cmd(show_temp)
  display.cmd(show_humi)

  display_data = display.read()

  print('Temperature: ', temp, 'Humidity: ', hum, 'Pressure: ', pres, '==>', display_data)  

  sleep(1)`

**Comment by talkyoo** [comment]
I did not saved the serial data, or put it otherwise overwrote it with None

**Comment by fstei** [comment]
Hello guys,

I am having pretty much the same problem as described above.
Based on @talkyoo's comment it seems they found a solution themself but I couldn't figure it out yet.

I tried to find out what the display sends to the MCU (ESP32 for me) after a button press by displaying it on a textfield on the display:
```
from nextion import nextion

display = nextion(1, 3, 9600)

while True:

data = display.read(nextion.RAW)
text = "t0.txt=\"" + str(data) + "\""
display.cmd(text)
```
all it showed in the textfield was "None".

In the Nextion Editor I ticked the "Send Component ID"  checkbox and wrote `print "ein"` as the Touch Release Event.
In the Debug mode pressing the button returns the following in the "Simulator Return:" Window:
`65 00 02 00 FF FF FF`  (push down)
`65 69 6E` (release)

Any idea how I could get this information to the MCU/ why I cant get it to work?

@gheinzer thanks a lot for creating this library, other than this issue it was very intuitive and the examples were very useful.

**Comment by gheinzer** [comment]
Hi @fstei 

Firstly, thanks a lot for you feedback. I really appreciate it.

So when you try to read from the display, but there is nothing the display sent, `display.read` returns `None` (this was not in the README, so I added it). So if you wouldn't have pressed the button, there would not be anything to read and date would be `None`.

I already had problems with having the TX and RX pins not connected correctly, so check if:
- You have connected TX and RX to the pins you have set in the code
- You have connected 5V and GND of the display to 5V and GND of you MCU and not some other power source
But I don't think that you got that wrong.

And another possibility: In your issue text it looks like you haven't indented the code after the `while True:`, so the code is only executed once:
- Nothing is available to be read, so data is `None`
- It sets the text field value to `None` and doesn't update the text field if you pressed the button.

Also note that if you want to have _ein_ showing up in your text field, I think you should use `nextion.DECODE` so the hexadecimal stuff is decoded to a string.

Aaaaand another thing: `print` is deprecated, so you could use `prints "ein",3` to get `ein` on your serial. And, as far as my knowledge goes, you don't have to use `Send Component ID`. That just sens some other junk to to the serial and in your case, you don't really need it. (That junk is the ID of the component, that is sent to serial in the event. You could also use that instead of `ein` to detect if the button is pressed)

Please excuse if I have written some things that you already know, but I hope it helps. Please let me know if it works or does not work.

**Comment by fstei** [comment]
Good Morning @gheinzer,

thank you so much for your fast and thorough response.

First off I changed `print "ein"` to `prints "ein",3` and unchecked `Send Component ID` and uploaded the new tft file.
I also used `nextion.DECODE` like you recommended.
The code after `while True:` is indented in my editor I just didn't know how to do it here on github.

I was using a different power source for the display. So I connected it to the ESP 32s 5V and GND. It turned on and worked like before. Only thing is: this way I have to plug in the 5V of the display after clicked run on my PC, otherwise the communication between the PC and the ESP 32 seems to be blocked. So I eventually went back to using the external power supply.

I think the problem might have to do with the TX and RX pins. This is the Pinout for reference:
![grafik](https://user-images.githubusercontent.com/103655885/163546608-8cba12e5-e68c-489a-bdbb-38c1cb57cee9.png)

I was using pin 1 and 3 like this: `display = nextion(1, 3, 9600)` connecting RX of the display to TX of the ESP and vice versa.
I used this simple bit of code to experiment:
```
from nextion import nextion
display = nextion(1, 3, 9600)

while True:
      display.cmd('t0.txt="test"')
```
- as expected this put "test" in the empty textbox.
- I disconnected (only) TX of the ESP and the textbox stayed empty
- I disconnected (only) RX of the ESP and the textbox stayed empty (I expected it to still work but somehow it didn't)
- I changed the code to `display = nextion(1, 4, 9600)` but left the cables on 1 and 3. This worked for some reason.
- I changed the code to `display = nextion(2, 3, 9600)` but left the cables on 1 and 3. This didn't work.
- I changed the code to `display = nextion(3, 1, 9600)` but left the cables on 1 and 3. This didn't work.

I dont really know how to interpret all this as it's not making a whole lot of sense to me.. maybe the RX pin of the ESP or the TX pin of the display isnt working? I really dont know

Again, thank you for your help so far. Do you have some other ideas on why its not working or things that I could try?

**Comment by gheinzer** [comment]
Hi again, @fstei

I think I know what the problem is.
So in the pinout, both pin 1 and 3 are marked with `U0 RX` or `U0 TX`. I think that is the serial connection that is used to communicate with your computer to upload programs, use the REPL etc. So if you connect RX and/or TX to these two pins, it breaks the communication with your computer.

According to the micropython docs (https://docs.micropython.org/en/latest/esp32/quickref.html#uart-serial-bus):

> Any GPIO can be used for hardware UARTs using the GPIO matrix, so to avoid conflicts simply provide tx and rx pins when constructing. The default pins listed below.

So, in my understanding, you don't have to use pins where _serial_ is written on the pinout. You could for example use pin 26 for TX and pin 27 for RX (or reversed). You would then use `display = nextion(26, 27, 9600)`. And then, I think it would be OK to use the 5V and GND pins on your ESP32 for the display to get it working.

I had the exact same issues with the power supply where I could send to the display, but was not able to receive anything.
I hope it works, let me know. Happy Easter!

**Comment by fstei** [comment]
Hey @gheinzer,
Happy Easter to you aswell!

I have got great news:
I connected TX and RX to normal GPIO Pins and I also used the ESPs 5V and GND for the displays power again. 
I am now able to upload/run scripts from PC to the ESP without having to disconnect the display like before. Also python `print()` funtion gives me an output in the editors shell (this didn't work before, presumably because communication to the PC was blocked like you mentioned).

I ran this code:
```
from nextion import nextion

display = nextion(26, 27, 9600)
display.cmd('t0.txt="test"')

while True:
    data = display.read(nextion.DECODE)
    print(str(data))
    if data != None:
        text = "t0.txt=\"" + str(data) +"\""
        display.cmd(text)
```
and it worked!! 
for the most part at least

I have two buttons on the nextion, one has the Touch Release Event `prints "ein",3` the other has `prints "aus",3`. Pressing them changes the content of the textbox which is good. The only thing is the data sent by the display isn't just the 3 character string that I entered in the nextion editor. Instead it sends `b'ein'` or `b'aus'` respectively. I assume the "b" stands for button. Do you know how I can make it so it only sends the string that I entered in the nextion editor? If not that's fine I can definitely work with this. Plus you already helped me more than you think.

One last thing: using that same code from above except with `data = display.read(nextion.RAW)` or `data = display.read()` returns the same `b'ein'` or `b'aus'` string. I was expecting something else but this is also not a huge problem for me just wanted to mention it.

Again thanks a lot!

**Comment by gheinzer** [comment]
Congrats!
The `b'ein'` is something python does if you try to convert the `bytes` datatype (that is for example returned by `display.read()`) to a `string` with `str()`. You can get it away by using `data.decode('utf-8')` as mentioned in https://stackoverflow.com/questions/606191/convert-bytes-to-a-string and https://docs.python.org/3/library/stdtypes.html#bytes.decode.
