### ISSUE TITLE
Read returns always b'\x00'

### ISSUE THREAD

**Issue by AngelMarinWolf** [programmer372/micropython-nextion#9]
Hi 

I tried to read data from Nextion Screen NX3224T024, the object uses pins 8,9 for tx,rx in a Raspberry Pi Pico. probably is not an issue with the module cause UART data always show b'\x00'.

**Comment by gheinzer** [comment]
Hi
I haven't tested this on a Raspberry Pi, but I don't think that the board is the problem. According to the documentation of Nextion (https://nextion.tech/instruction-set/#s7), the value that you got stands for an invalid instruction. So the issue is, in my understanding, not in the connection or this module but the commands that you have sent to your display.
